#! /usr/bin/env bash

set -euo pipefail

shared_config_loaded=${shared_config_loaded:-0}
if [ "x0" == "x${shared_config_loaded}" ]; then
  shared_config_loaded=1

  shared_install_location=${shared_install_location:-"/opt/sascha-andres/shared-shell"}
  shared_debug=${shared_debug:-0}
fi

if [ "x1" == "x${shared_debug}" ]; then
  set -x
fi